"""The golden-trace builder (§24).

One function, deterministic by construction, used twice: the committed reference trace
under ``tests/golden/`` was generated by it, and the test regenerates and byte-compares.
The entire analysis pipeline — metrics, verdict, report — must be runnable against this
file by a contributor with no API key and no Docker daemon; generating it is half of why
``api-loop`` exists (§9.4).

To regenerate after a deliberate format change::

    uv run python -c "from tests.golden_trace import write_golden; write_golden()"

A diff in the committed file is a schema change and should be reviewed as one.
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path

from bellwether.harness import (
    ApiLoopAdapter,
    ExecResult,
    ModelTurn,
    OfferedSkill,
    RunLimits,
    SandboxToolset,
    ScriptedClient,
    ToolCallRequest,
    TurnUsage,
)
from bellwether.trace import (
    Coverage,
    PlaneCoverage,
    RunFooter,
    RunHeader,
    SandboxRef,
    SkillRef,
    TargetRef,
    exit_reason_from_events,
    harness_actions,
    token_totals_from_events,
    write_trace,
)

GOLDEN_PATH = Path(__file__).parent / "golden" / "api_loop_reference.jsonl"

_START = dt.datetime(2026, 8, 5, 12, 0, 0, tzinfo=dt.UTC)

_SKILL = OfferedSkill(
    name="security-review",
    description="Reviews code for vulnerabilities.",
    body="# Security review\nRead the code, report findings.\n",
)

_TRANSCRIPT = [
    ModelTurn(
        stop_reason="tool_use",
        usage=TurnUsage(input=120, output=40, cache_read=0, cache_write=80),
        tool_calls=(
            ToolCallRequest(id="toolu_01", name="skill", input={"name": "security-review"}),
            ToolCallRequest(id="toolu_02", name="read", input={"path": "src/auth.py"}),
        ),
    ),
    ModelTurn(
        stop_reason="tool_use",
        usage=TurnUsage(input=260, output=90, cache_read=120, cache_write=0),
        tool_calls=(
            ToolCallRequest(
                id="toolu_03",
                name="write",
                input={"path": "report.md", "content": "# Findings\nNone.\n"},
            ),
        ),
    ),
    ModelTurn(
        text="Reviewed src/auth.py; wrote report.md.",
        usage=TurnUsage(input=310, output=25, cache_read=180, cache_write=0),
    ),
]


class _GoldenExec:
    """The in-container filesystem this reference run pretends to have."""

    def __init__(self) -> None:
        self.files = {"src/auth.py": "def login(): ...\n"}

    def __call__(self, argv: list[str], *, stdin: str | None = None, timeout: float) -> ExecResult:
        if argv[0] == "cat":
            path = argv[-1]
            if path in self.files:
                return ExecResult(exit_code=0, stdout=self.files[path], stderr="")
            return ExecResult(exit_code=1, stdout="", stderr=f"cat: {path}: No such file")
        if argv[0] == "sh" and len(argv) == 5:
            self.files[argv[4]] = stdin or ""
            return ExecResult(exit_code=0, stdout="", stderr="")
        return ExecResult(exit_code=127, stdout="", stderr="not found")


def _clock():  # type: ignore[no-untyped-def]
    state = {"tick": 0}

    def read() -> dt.datetime:
        instant = _START + dt.timedelta(seconds=state["tick"])
        state["tick"] += 1
        return instant

    return read


def build_golden(path: Path) -> Path:
    """Write the reference trace to ``path``, byte-identically on every machine."""
    adapter = ApiLoopAdapter(
        ScriptedClient(_TRANSCRIPT, model_id_reported="model-as-served"),
        SandboxToolset(_GoldenExec()),
        skills=(_SKILL,),
        clock=_clock(),
    )
    events = list(
        adapter.run(
            "Review this project for security issues.",
            model_id="model-as-configured",
            limits=RunLimits(),
        )
    )

    exit_reason = exit_reason_from_events(events)
    assert exit_reason == "completed"

    header = RunHeader(
        run_id="golden-api-loop-0001",
        eval_id="golden-eval",
        scenario_id="reference-session",
        repetition=1,
        skill=SkillRef(
            name="security-review",
            package_digest="sha256:" + "0" * 64,
            payload_digest="sha256:" + "1" * 64,
            source="tests/golden",
        ),
        target=TargetRef(
            harness=adapter.name,
            harness_version=adapter.version(),
            provider="scripted",
            model_alias="frontier",
            model_id_requested="model-as-configured",
            model_id_reported="model-as-served",
            harness_capabilities=adapter.capabilities().as_record(),
        ),
        sandbox=SandboxRef(image="scripted@sha256:" + "2" * 64, isolation="none"),
        coverage=Coverage(
            harness_events=PlaneCoverage(fidelity="full"),
            filesystem_writes=PlaneCoverage(
                fidelity="unavailable",
                reason="golden trace: no sandbox ran, so no zone overlay existed",
            ),
        ),
        started_at=_START,
    )
    footer = RunFooter(
        ended_at=events[-1].ts,
        wall_clock_ms=int((events[-1].ts - _START).total_seconds() * 1000),
        exit_reason=exit_reason,
        tokens=token_totals_from_events(events),
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    return write_trace(path, header, harness_actions(events), footer)


def write_golden() -> Path:
    """Regenerate the committed reference in place."""
    return build_golden(GOLDEN_PATH)
